---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rapidast-e2e
spec:
  params:
    - name: repo_url
      default: github.com/sfowl/rapidast
    - name: revision
      default: "development"
    - name: image
      default: quay.io/redhatproductsecurity/rapidast:latest
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: |-
          '{
            "components": [
              {
                "name":"rapidast",
                "containerImage": "quay.io/redhatproductsecurity/rapidast:latest",
                "source":{
                  "git":{
                    "url":"git@github.com:sfowl/rapidast.git",
                    "revision":"development",
                  }
                }
              }
            ]
          }'
      type: string

  tasks:
    - name: task-1
      description: Placeholder task that prints the Snapshot and outputs standard TEST_OUTPUT
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      taskSpec:
        params:
        - name: SNAPSHOT
        results:
        - name: TEST_OUTPUT
          description: Test output
        steps:
        - image: registry.redhat.io/openshift4/ose-cli:latest
          env:
          - name: SNAPSHOT
            value: $(params.SNAPSHOT)
          script: |
            dnf -y install jq
            echo -e "Example test task for the Snapshot:\n ${SNAPSHOT}"

            # echo "checking oc.."
            # oc get pods
            # oc whoami
            # Run custom tests for the given Snapshot here
            # After the tests finish, record the overall result in the RESULT variable
            RESULT="SUCCESS"

            # Output the standardized TEST_OUTPUT result in JSON form
            TEST_OUTPUT=$(jq -rc --arg date $(date -u --iso-8601=seconds) --arg RESULT "${RESULT}" --null-input \
              '{result: $RESULT, timestamp: $date, failures: 0, successes: 1, warnings: 0}')
            echo -n "${TEST_OUTPUT}" | tee $(results.TEST_OUTPUT.path)

    - name: provision-eaas-space
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: task/eaas-provision-space/0.1/eaas-provision-space.yaml
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)
    - name: provision-cluster
      runAfter:
        - provision-eaas-space
      taskSpec:
        results:
          - name: clusterName
            value: "$(steps.create-cluster.results.clusterName)"
        volumes:
          - name: credentials
            emptyDir: {}
        steps:
          - name: get-supported-versions
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-supported-ephemeral-cluster-versions/0.1/eaas-get-supported-ephemeral-cluster-versions.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
          - name: pick-version
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-latest-openshift-version-by-prefix/0.1/eaas-get-latest-openshift-version-by-prefix.yaml
            params:
              - name: prefix
                value: "$(steps.get-supported-versions.results.versions[0])."
          - name: create-cluster
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: version
                value: "$(steps.pick-version.results.version)"
          - name: get-kubeconfig
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: clusterName
                value: "$(steps.create-cluster.results.clusterName)"
              - name: credentials
                value: credentials
  #   pipelineSpec:
  #     params:
  #       - name: repo_url
  #       - name: revision
  #       - name: SNAPSHOT
  #         value: $(params.SNAPSHOT)
  #     workspaces:
  #       - name: source
  #     tasks:
  #       - name: fetch-repository
  #         taskRef:
  #           name: git-clone
  #         workspaces:
  #           - name: output
  #             workspace: source
  #           - name: ssl-ca-directory
  #             workspace: redhat-ca-directory
  #         params:
  #           - name: url
  #             value: $(params.repo_url)
  #           - name: revision
  #             value: $(params.revision)
  #
  #       - name: run-tests
  #         runAfter:
  #           - fetch-repository
  #         workspaces:
  #           - name: source
  #             workspace: source
  #         taskSpec:
  #           workspaces:
  #             - name: source
  #           steps:
  #             - name: run-tests
  #               image: registry.redhat.io/openshift4/ose-cli:latest
  #               workingDir: $(workspaces.source.path)
  #               env:
  #               - name: RAPIDAST_IMAGE
  #                 value: $(params.image)
  #               script: |
  #                 yum install -y python3.12
  #                 python3.12 -m ensurepip
  #                 pip3 install -r requirements.txt
  #                 pytest -s e2e-tests
