apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: experiment-test
  labels:
    test.appstudio.openshift.io/optional: "true"
spec:
  application: rapidast
  contexts:
  - description: Application testing
    name: application
  resolverRef:
    params:
    - name: url
      value: https://github.com/sfowl/rapidast
    - name: revision
      value: {{ revision }}
    - name: pathInRepo
      value: e2e-tests/manifests/integration-test-pipeline.yaml
    resolver: git
